### PR TITLE
Fix: Intel classic (icpc) build error "EKinetic is not a template"

### LINKED ISSUE #7927: Intel classic (icpc) build fails: "EKinetic is not a template" — out-of-line destructor of a partial specialization named with a template argument list
### Describe the bug

With Intel classic compilers (icpc 2022.1), compiling `source/source_lcao/module_operator_lcao/ekinetic.cpp` fails with:

```text
ekinetic.cpp(36): error: EKinetic is not a template
```

Reproduces with LCAO + LIBRI + PEXSI + MLALGO features enabled. icpx and GCC accept the same code.

### Root cause

`ekinetic.cpp:36` defines the destructor of the partial specialization `EKinetic<OperatorLCAO<TK, TR>>` out of class, with the template argument list attached to the destructor name:

```cpp
template <typename TK, typename TR>
hamilt::EKinetic<hamilt::OperatorLCAO<TK, TR>>::~EKinetic<hamilt::OperatorLCAO<TK, TR>>()
```

After `~`, icpc's EDG frontend looks up `EKinetic` and finds the injected-class-name of the partial specialization — a type, not usable as a template name in this context — so it cannot attach the `<...>` argument list and reports `EKinetic is not a template`. Naming the destructor of a partial specialization with a template-id in an out-of-class definition is a gray-zone construct: GCC/Clang (icpx) accept it as denoting the current instantiation, while EDG rejects it. Intel classic is frozen, so no compiler-side fix is coming.

This regression was introduced by bbd23ca03 (2026-09-02, "DFT+U refactor, step 6", #7879), which changed the previously plain form `~EKinetic()` into the template-argument form. Builds before that commit compile fine with icpc, which is why older versions did not hit this.

### Correction of the original analysis

The first version of this issue blamed the `#ifndef __EKINETICTEMPLATE` inner guard shared by `ekinetic.h` and `op_pw_ekin.h`. That theory was disproved: after removing the shared guard, icpc still failed with the same error. Preprocessing plus a minimal reproducer identified the destructor form above as the real cause. (The shared guard is still a separate, currently-unreachable latent hazard — any TU that includes both headers, in either order, fails on GCC too — and the same PR cleans it up.)

### Expected behavior

Builds successfully.

### Environment

Intel classic compiler (icpc) 2022.1 on Rocky Linux release 8.8.

### Additional Context

Fix: name the out-of-line destructor without the template argument list (`~EKinetic()`); with this change `ekinetic.cpp` compiles directly under icpc 2022.1.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

### PR DESCRIPTION
**Pull request by Flying-dragon-boxing**
### Reminder
- [x] I have read `AGENTS.md` and `docs/developers_guide/agent_governance.md`.
- [x] I have linked an issue or explained why this PR does not need one.
- [x] I have added adequate unit tests and/or case tests, or explained why not.
- [x] I have listed the exact verification commands run and their results.
- [x] I have described user-visible behavior changes, including INPUT parameter changes.
- [x] I have explained core-module impact for ESolver, HSolver, ElecState, Hamilt, Operator, Psi, or other `source/` changes.
- [x] I have requested any needed governance exception below.

### Linked Issue
Fix #7927

### Unit Tests and/or Case Tests for my changes
- Commands run:
  - `icpc` 2022.1 (Intel classic, Rocky Linux 8.8, LCAO+LIBRI+PEXSI+MLALGO enabled): direct compilation of `source/source_lcao/module_operator_lcao/ekinetic.cpp` — previously failing with `error: EKinetic is not a template`, now compiles.
  - `g++ -std=gnu++14 -fsyntax-only source/source_lcao/module_operator_lcao/ekinetic.cpp` with the standard ABACUS define set (`__EXX`, `__LCAO`, `__MPI`, ...), GCC 11.4.0.
  - `g++ -std=gnu++14 -fsyntax-only source/source_pw/module_pwdft/op_pw_ekin.cpp` (same flags).
  - Forced dual-include TUs (`op_pw_ekin.h` + `ekinetic.h`, both include orders) with `g++ -std=gnu++11 -fsyntax-only`: previously failing on GCC with `'EKinetic'/'Ekinetic' is not a class template`; now clean in both orders.
- Result summary: all pass.
- Checks not run, with reason: no new unit test added — this is a compile-compatibility fix with zero runtime behavior change; no Intel classic CI exists, and the affected TUs are covered by the existing GCC/icpx CI builds.

### What's changed?
- `source_lcao/module_operator_lcao/ekinetic.cpp`: the out-of-line destructor of the partial specialization `EKinetic<OperatorLCAO<TK,TR>>` is named plainly again (`~EKinetic()`), reverting the template-argument form `~EKinetic<hamilt::OperatorLCAO<TK, TR>>()` introduced by bbd23ca03 (#7879), which icpc's EDG frontend cannot resolve ("EKinetic is not a template"; the injected-class-name of the partial specialization is found as a type and cannot take a template argument list in this context). GCC/Clang(icpx) accept both forms, so GCC CI never caught it.
- `source_lcao/module_operator_lcao/ekinetic.h`, `source_pw/module_pwdft/op_pw_ekin.h`: removed the inner `#ifndef __EKINETICTEMPLATE` guard blocks. Both headers shared that one macro, so any TU including both headers (in either order) skipped the second primary template and failed — on any compiler, GCC included (currently unreachable in our build graph, but a latent hazard). The outer include guards already prevent double inclusion, and the change also drops the reserved double-underscore identifier.

### Governance Notes
- INPUT/docs changes: none; no user-visible behavior change.
- Core module impact: Operator layer only (LCAO kinetic operator definition + PW kinetic operator header). No runtime behavior change.
- Exceptions requested: none.

### CODE REVIEW

File: source/source_pw/module_pwdft/op_pw_ekin.h [hunk 1]
```diff
@@ -8,15 +8,7 @@
 
 namespace hamilt {
 
-// Not needed anymore
```
Comment (Flying-dragon-boxing) [inline source/source_pw/module_pwdft/op_pw_ekin.h]: Removed since not needed anymore. Still, using `Ekinetic` for PW and `EKinetic` for NAO is not a good idea.

**Review by mohanchen — APPROVED** [review]
