### ISSUE TITLE
Intel classic (icpc) build fails: "EKinetic is not a template" — out-of-line destructor of a partial specialization named with a template argument list

### ISSUE THREAD

**Issue by Flying-dragon-boxing** [deepmodeling/abacus-develop#7927]
### Describe the bug

With Intel classic compilers (icpc 2022.1), compiling `source/source_lcao/module_operator_lcao/ekinetic.cpp` fails with:

```text
ekinetic.cpp(36): error: EKinetic is not a template
```

Reproduces with LCAO + LIBRI + PEXSI + MLALGO features enabled. icpx and GCC accept the same code.

### Root cause

`ekinetic.cpp:36` defines the destructor of the partial specialization `EKinetic<OperatorLCAO<TK, TR>>` out of class, with the template argument list attached to the destructor name:

```cpp
template <typename TK, typename TR>
hamilt::EKinetic<hamilt::OperatorLCAO<TK, TR>>::~EKinetic<hamilt::OperatorLCAO<TK, TR>>()
```

After `~`, icpc's EDG frontend looks up `EKinetic` and finds the injected-class-name of the partial specialization — a type, not usable as a template name in this context — so it cannot attach the `<...>` argument list and reports `EKinetic is not a template`. Naming the destructor of a partial specialization with a template-id in an out-of-class definition is a gray-zone construct: GCC/Clang (icpx) accept it as denoting the current instantiation, while EDG rejects it. Intel classic is frozen, so no compiler-side fix is coming.

This regression was introduced by bbd23ca03 (2026-09-02, "DFT+U refactor, step 6", #7879), which changed the previously plain form `~EKinetic()` into the template-argument form. Builds before that commit compile fine with icpc, which is why older versions did not hit this.

### Correction of the original analysis

The first version of this issue blamed the `#ifndef __EKINETICTEMPLATE` inner guard shared by `ekinetic.h` and `op_pw_ekin.h`. That theory was disproved: after removing the shared guard, icpc still failed with the same error. Preprocessing plus a minimal reproducer identified the destructor form above as the real cause. (The shared guard is still a separate, currently-unreachable latent hazard — any TU that includes both headers, in either order, fails on GCC too — and the same PR cleans it up.)

### Expected behavior

Builds successfully.

### Environment

Intel classic compiler (icpc) 2022.1 on Rocky Linux release 8.8.

### Additional Context

Fix: name the out-of-line destructor without the template argument list (`~EKinetic()`); with this change `ekinetic.cpp` compiles directly under icpc 2022.1.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).
