### PR TITLE
Fix: Compiling error for ROCM

### LINKED ISSUE #5414: Daily DCU test failed since 20241102
### Describe the bug

Since 20241102, the DCU test is failed because of compile error. This error is introduced by commits between 0f44046 (tested at 20241102, and is failed) and 3984296 (tested at 20241101, and is passed).

The error is related to force/stress, which may be introduced by commit e276480937.

@dyzheng , could you have a check?

Image

The error message is:
```
/public/home/abacus/abacus-dcu/source/module_hamilt_pw/hamilt_pwdft/kernels/rocm/stress_op.hip.cu:294:5: error: use of undeclared identifier '__syncwarp'; did you mean '__sync_swap'?
    __syncwarp();
    ^~~~~~~~~~
    __sync_swap
/public/home/abacus/abacus-dcu/source/module_hamilt_pw/hamilt_pwdft/kernels/rocm/stress_op.hip.cu:294:5: note: '__sync_swap' declared here
/public/home/abacus/abacus-dcu/source/module_hamilt_pw/hamilt_pwdft/kernels/rocm/stress_op.hip.cu:294:16: error: too few arguments to function call, expected at least 1, have 0
    __syncwarp();
    ~~~~~~~~~~ ^
[ 70%] Building CXX object source/module_io/CMakeFiles/io_basic.dir/read_wfc_to_rho.cpp.o
2 errors generated when compiling for gfx906.
[ 70%] Building CXX object source/module_cell/CMakeFiles/cell.dir/read_pp_vwr.cpp.o
CMake Error at device_rocm_generated_stress_op.hip.cu.o.cmake:180 (message):
  Error generating file
  /public/home/abacus/abacus-dcu/build-dcu/source/CMakeFiles/device_rocm.dir/module_hamilt_pw/hamilt_pwdft/kernels/rocm/./device_rocm_generated_stress_op.hip.cu.o


make[2]: *** [source/CMakeFiles/device_rocm.dir/build.make:147: source/CMakeFiles/device_rocm.dir/module_hamilt_pw/hamilt_pwdft/kernels/rocm/device_rocm_generated_stress_op.hip.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

### Expected behavior

_No response_

### To Reproduce

_No response_

### Environment

_No response_

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

### PR DESCRIPTION
**Pull request by dyzheng**
### Reminder
- [ ] Have you linked an issue with this pull request?
- [ ] Have you added adequate unit tests and/or case tests for your pull request?
- [ ] Have you noticed possible changes of behavior below or in the linked issue?
- [ ] Have you explained the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi? (ignore if not applicable)

### Linked Issue
Fix #5414 

### Unit Tests and/or Case Tests for my changes
- A unit test is added for each new feature or bug fix.

### What's changed?
- Example: My changes might affect the performance of the application under certain conditions, and I have tested the impact on various scenarios...

### Any changes of core modules? (ignore if not applicable)
- Example: I have added a new virtual function in the esolver base class in order to ...

### CODE REVIEW

**Comment by dyzheng** [comment]
img_v3_02gi_b08602e2-149d-45d5-9c65-26014eb6b8ag
@Qianruipku still error after this PR

**Review by mohanchen — APPROVED** [review]
