### ISSUE TITLE
Build fails after merging PR #7888 and PR #7900

### ISSUE THREAD

**Issue by AsTonyshment** [deepmodeling/abacus-develop#7911]
After PR #7888 and PR #7900 were merged, building with MPI and unit tests enabled fails:

```text
error: ‘world_communication_domain’ is not a member of ‘ModuleBase’
```

PR #7900 renamed `ModuleBase::world_communication_domain()` to `ModuleBase::world_comm_domain()`, but five calls introduced by PR #7888 still use the old name.

## Reproduction

With the required build dependencies configured:

```bash
cmake -S . -B build -DENABLE_MPI=ON -DBUILD_TESTING=ON
cmake --build build -j32
```

## Affected files

Under `source/source_base/test_parallel/`:

- `test_para_gemm.cpp:77`
- `parallel_device_test.cpp:127`
- `parallel_domain_grid_test.cpp:17,31,49`

## Suggested fix

Update these five calls to `ModuleBase::world_comm_domain()`, then rebuild and run the affected tests.

PR #7888 and PR #7900 each passed their pre-merge CI without including the other's changes. The post-merge CMake Build Test used `BUILD_TESTING=OFF`, so it did not catch this incompatibility. [PR #7900 CI](https://github.com/deepmodeling/abacus-develop/actions/runs/33842296005/job/100926884753), [PR #7888 CI](https://github.com/deepmodeling/abacus-develop/actions/runs/33853787596/job/100962287964), [post-merge build](https://github.com/deepmodeling/abacus-develop/actions/runs/33876914128/job/101035981150).
