### ISSUE TITLE
Compile Error: Conflicts between PR#5298 and #5312

### ISSUE THREAD

**Issue by Cstandardlib** [deepmodeling/abacus-develop#5330]
### Describe the bug

After #5298 and #5312 were merged simultaneously, the compiler raises an error:
```bash
In file included from ./module_lr/operator_casida/operator_lr_hxc.cpp:1:
./module_lr/operator_casida/operator_lr_hxc.h:50:22: error: 'act' marked 'override' but does not override any member functions
   50 |         virtual void act(const int nbands, const int nbasis, const int npol, const T* psi_in, T* hpsi, const int ngk_ik = 0)const override;
      |                      ^
./module_lr/operator_casida/operator_lr_hxc.cpp:54:10: note: in instantiation of template class 'LR::OperatorLRHxc<>' requested here
   54 |     void OperatorLRHxc<double, base_device::DEVICE_CPU>::grid_calculation(const int& nbands) const
      |          ^
```
In #5298 the interface of act is refactored to take a new parameter
![Image](https://github.com/user-attachments/assets/33f735be-c061-4701-a133-43f11efebe12)

While #5312 does not override the new `act`
![Image](https://github.com/user-attachments/assets/e50d4abf-52dd-4379-a0ce-bcfea1eccbdd)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by Cstandardlib** [comment]
Will be fixed by #5329
